stages:
  - build-nginx

variables:
  IMAGE_TAG1: $CI_REGISTRY_IMAGE:nginx-srv

Build Nginx:
  stage: build-nginx
  tags:
    - linux-sddc
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:  
    - docker build -t $IMAGE_TAG1 04-Apache-Nginx/nginx/
    - docker push $IMAGE_TAG1
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build/
    