version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-dockers
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - $DEFAULT_NETWORK
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
networks:
  web:
    external:
      name: $DEFAULT_NETWORK
