apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-vol-pers
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/web