apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      deploy: apache
  template:
    metadata:
      labels:
       deploy: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine
        volumeMounts:
        - name: web-vol-pers
          mountPath: /usr/local/apache2/htdocs/web
      volumes: 
      - name: web-vol-pers
        hostPath:
          path: /data/web 