[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$nxFZn.K7$Z0fxtkRSUt8NvtqGuqG3O/"
  ]

[http.routers.api]
  rule = "Host(`admin_blog.org`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
